# Generated by Django 5.2.1 on 2025-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoModel',
            fields=[
                ('nr_os_lis', models.IntegerField(primary_key=True, serialize=False)),
                ('nr_os_externo', models.IntegerField(blank=True)),
                ('solicitante', models.CharField(max_length=50)),
                ('ts_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('servico', models.IntegerField(choices=[(0, 'Desenvolvimento'), (1, 'Manutenção'), (2, 'Calibração'), (3, 'Treinamento')])),
                ('descricao', models.CharField(max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Aberta'), (1, 'Iniciada'), (2, 'Concluída')], default=0)),
                ('responsavel', models.CharField(max_length=50, null=True)),
                ('ts_inicio', models.DateTimeField(null=True)),
                ('ts_conclusao', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ordens_servico',
            },
        ),
    ]
